instagram/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from webapp import settings

#all URLs are directed here after looking up in the project URLs folder except the admin account

app_name='instagram'
urlpatterns = [
    url(r'^$', views.homepage, name='home'),
    url(r'login/', views.login1, name='login'),
    url(r'signup/', views.signup, name='signup'),
    url(r'logout/', views.logout1, name='logout'),
    url(r'delete/', views.delete, name='delete'),
    url(r'edit/', views.edit, name='edit'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from instagram import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^instagram/', include('instagram.urls')), #url for the user page directs you to the applications url file
    url(r'^$', views.home, name="home1")  #url for the viewer page
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instagram/models.py
from django.db import models
from django.contrib.auth.models import User

#Data fields model that is to be stored in the sqlite3 database
class Post(models.Model):
    
    image_field= models.FileField(null=True, blank=True)
    
    pub_date = models.DateTimeField( )
    
    # models.cascade deletes all the data associated with the deleted object 
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    caption= models.CharField(max_length=250)
    

instagram/forms.py
from django import forms

class ImageUpload(forms.Form):
    image_field = forms.FileField(
        label='Click to browse computer',
        help_text='Only jpeg, png and gif allowed: ')

    #require should be set to false to upload image without a caption
    caption = forms.CharField(max_length=100,label='Enter a Caption',required=False)

instagram/views.py
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.template import loader
from PIL import Image
from webapp import settings
from django.utils import timezone
import os
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import ImageUpload
from .models import Post

#This is a function that processes the data and passes it to the HTML files for the viewer's page along with user's page
def home(request):
    if request.user.is_authenticated:   #if user is authenticated he stays in the user view
        if request.method == 'POST':
            form = ImageUpload(request.POST,request.FILES)
            if form.is_valid():
                updated_post = Post(image_field=request.FILES['image_field'],user=request.user,caption=form.cleaned_data['caption'],pub_date=timezone.datetime.now())
                updated_post.save()
                try:
                    check_image = Image.open(settings.MEDIA_ROOT +'/'+str(updated_post.image_field))
                    if check_image.format not in ('GIF', 'PNG', 'JPEG'):
                        Omit(updated_post.id)
                except Exception:
                    Omit(updated_post.id)
                return HttpResponseRedirect('#')
        else:
            form=ImageUpload()
        uploads = Post.objects.filter(user=request.user).order_by('-pub_date')
        paginator = Paginator(uploads, 10) #Displays only 10 images per page
        page = request.GET.get('page')
        try:
            photos = paginator.page(page)
        except PageNotAnInteger:
            photos = paginator.page(1)
        except EmptyPage:
            photos = paginator.page(paginator.num_pages)

        template = loader.get_template('instagram/homepage.html')
        context = {
            'uploads': photos,
            'username':request.user,
            'form':form
        }
        return HttpResponse(template.render(context, request))
    
    #if user is not authenticated then he is directed to the only viewer page. 

    else:   
        uploads = Post.objects.order_by('-pub_date')
        paginator = Paginator(uploads, 10) 
        page = request.GET.get('page')
        try:
            photos = paginator.page(page)
        except PageNotAnInteger:
            photos = paginator.page(1)
        except EmptyPage:
            photos = paginator.page(paginator.num_pages)
        template = loader.get_template('instagram/homepage.html') 
        context = {
            'uploads': photos,
            'username':request.user,
        }
        return HttpResponse(template.render(context, request))

#this is the function that processes data and passes it on to the User View HTML file 
def homepage(request):
    if request.user.is_authenticated: #if user is authenticated he stays in the user view
        if request.method == 'POST':
            form = ImageUpload(request.POST,request.FILES)
            if form.is_valid():
                updated_post = Post(image_field=request.FILES['image_field'],user=request.user,caption=form.cleaned_data['caption'],pub_date=timezone.datetime.now())
                updated_post.save()
                try:
                    check_image = Image.open(settings.MEDIA_ROOT +'/'+str(updated_post.image_field))
                    if check_image.format not in ('GIF', 'PNG', 'JPEG'):
                        Omit(updated_post.id)
                except Exception:
                    Omit(updated_post.id)
                return HttpResponseRedirect('#')
        else:
            form=ImageUpload()
        uploads = Post.objects.filter(user=request.user).order_by('-pub_date')
        paginator = Paginator(uploads, 10) #Displays only 10 images per page
        page = request.GET.get('page')
        try:
            photos = paginator.page(page)
        except PageNotAnInteger:
            photos = paginator.page(1)
        except EmptyPage:
            photos = paginator.page(paginator.num_pages)

        template = loader.get_template('instagram/homepage.html') 
        context = {
            'uploads': photos,
            'username':request.user,
            'form':form
        }
        return HttpResponse(template.render(context, request))
    else:
        template = loader.get_template('instagram/login.html')
        return HttpResponse(template.render(None, request))


#this is a signup function for the user to signup for an account
def signup(request):
    if request.method =='POST':
        if request.POST['password1'] == request.POST['password2']: #processes only if both passwords are the same
            try:
                user= User.objects.get(username=request.POST['username'])
                return render(request, 'instagram/signup.html',{'error':'Username has already been taken'}) #sends error if username already exists
            except User.DoesNotExist:
                user = User.objects.create_user(request.POST['username'], password= request.POST['password1'])
                login(request, user)
                return render(request, 'instagram/login.html')
        else:
            return render(request, 'instagram/signup.html',{'error':'Passwords didn\'t match'}) #otherwise sends an error message 
    else:
        return render(request, 'instagram/signup.html')


#this is a login function for the user to login to his account

def login1(request):
    if request.method == 'POST':
        username=request.POST['username']
        password=request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/instagram')
        else:
            return render(request, 'instagram/login.html',{'error':'Username and Password didn \'t match'}) #sends error if username and password don't match
    else:
        return render(request, 'instagram/login.html')

#this is a logout function for the user to logout of his account

def logout1(request):
    if request.user.is_authenticated:
	    logout(request)
    return HttpResponseRedirect('/')

#This is a function that edits the caption of the image
def edit(request): 
	caption_update = request.GET.get('caption')
	fetch=Post.objects.filter(id=request.GET.get('id')).update(caption=caption_update)
	return HttpResponseRedirect('/instagram')

#this is a delete function that deletes a photo 

def delete(request):
	fetch=Post.objects.filter(id=request.GET.get('id'))
	deleteFile(settings.MEDIA_ROOT +'/'+str(fetch[0].image_field))
	fetch.delete()
	return HttpResponseRedirect('/instagram')

#this function deletes a photo from the database using the ID.
def Omit(pid):
	fetch=Post.objects.filter(id=pid)
	deleteFile(settings.MEDIA_ROOT +'/'+str(fetch[0].image_field))
	fetch.delete()

#photo deleted from the filesystem
def deleteFile(filename):
	try:
		os.remove(filename)
	except OSError:
		print('couldnt delete file')

instagram/templates/instagram/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
        <!-- <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet"> -->
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="/instagram">Instagram</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse " id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item active">
                        <a class="nav-link" href="#" onClick="document.getElementById('logout').submit()">Logout <span class="sr-only">(current)</span></a>
                    <form id="logout" method="POST" action="{% url 'instagram:logout' %}">
                        {% csrf_token %}
                        <input type="hidden">
                    </li>
                    {% else %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'instagram:signup'  %}">Sign-up <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'instagram:login'  %}">Login <span class="sr-only">(current)</span></a>
                    </li>
                    {% endif %}
                
                </ul>
            </div>
        </nav>
        <div class="container col-xs-12">
            {% block content%}            
            {% endblock  %}
        </div>
    <footer class="footer navbar-fixed-bottom">
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Photogram	 2016</p>
            </div>
        </div>
	</footer>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  </body>
</html>

instagram/templates/instagram/homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="author" content="Sumedh_Karande">
		<title>Instagram</title>
		
		<!-- Bootstrap -->
		
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" href="{% static 'instagram/style.css' %}" />
	</head>
	
	<!-- If user is Authenticated it shows the user page view irrespective -->

	{% if user.is_authenticated %}

	<!-- NAVBAR -->

		<nav class="navbar navbar-inverse navbar-default">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynav">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" style="color: white" href="/instagram">Instagram</a>
				</div>
				<div class="collapse navbar-collapse" id="mynav"> 
					<ul class="nav navbar-nav navbar-right">
						<li class="nav-item">
						<a class="nav-link" style="color: white" href="/instagram/logout">Logout</a>
						</li>
					</ul>
				</div> 
			</div>
		</nav>

		<!-- BODY OF THE USER'S VIEW PAGE -->

		<div align="center">
			<h2 class="align-center">Welcome to Instagram, {{ username }} !</h2>
		</div>
		<br />
		<div class="container" align="center" style="font-size:20px;">
			<div class="container well">
				<form class="form-inline" action="#" method="post" enctype="multipart/form-data">
					{% csrf_token %} {{form}} <br />
					<input type="submit"  class="btn btn-info" value="Upload" />
				</form>
			</div>
			<div class="row ">
				<div class="col-lg-12">
					<h1 class="page-header center">{{ username }}'s Photos</h1>
				</div>
			</div>


			{% if uploads %}
			
				{% for photo in uploads %}
					<br />	
					<div class="col-lg-12 col-md-12 col-xs-12 well">
						<div class="container-fluid bg-3 text-center">
							<h3>{{photo.caption}}</h3>
						</div><br />
						<img class="img-responsive" height="236" src="media/{{photo.image_field}}" >
					</div><br />
					<a href="delete?id={{photo.id}}" class="btn btn-info" onclick="return confirm('Sure about it?');">Delete</a>
					<input type="button" class="btn btn-info" onclick="var t = prompt('Edit Caption', '{{photo.caption}}'); if (t!= null) window.location.href='edit?id={{photo.id}}&caption='+t " value='Edit Caption'></input><br />						
				{% endfor %}
				
				<div class="pagination">
					<span class="step-links">
						{% if uploads.has_previous %}
							<a href="?page={{ uploads.previous_page_number }}">previous</a>
						{% endif %}

						<span class="current">
						<h4>	Page {{ uploads.number }} of {{ uploads.paginator.num_pages }}. </h4>
						</span>

						{% if uploads.has_next %}
							<a class="btn btn-primary" href="?page={{ uploads.next_page_number }}">next</a>
						{% endif %}
					</span>
				</div>
			{% else %}
				<h3 >You have no Images at the moment!</h3>
				<h2 >Click to Upload!</h2>
			
			{% endif %}
		</div>

	<!-- If user is not logged in, then the viewer is shown the Viewer page -->
		
	{% else %}
		
	<!-- BODY OF THE STRICTLY VIEWER'S VIEW -->


		<nav class="navbar navbar-inverse navbar-default">
			<div class="container">
				<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynav">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" style="color: white" href="#">Instagram</a>
				</div>
				<div class="collapse navbar-collapse" id="mynav"> 
					<ul class="nav navbar-nav navbar-right">
						<li class="nav-item">
							<a class="nav-link" style="color: white" href="/instagram/signup">Sign-up</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" style="color: white" href="/instagram/login">Login</a>
						</li>
					</ul>
				</div> 
			</div>
		</nav>
		<div align="center">
			<h2 class="align-center">Welcome to Instagram!</h2>
			<h3 class="align-center">Login to share your memories with your friends</h3>
		</div><br />
		<div class="container" align="center" style="font-size:20px;">
			{% for photo in uploads %}
				<div class="col-lg-12 col-md-12 col-xs-12 well">
					<div class="custom-container text-center">
						<h2>{{photo.caption}}</h2>
						<h3 class="page-header center">User- {{ photo.user }}</h3>
					</div>
					<div class="center " align="center">
						<img class="img-responsive" width="500" height= "236" src="media/{{photo.image_field}}" alt="">	
					</div>
				</div>
			{% endfor %}
			
			<div class="col-lg-12 col-md-12 col-xs-12">
				<div class="pagination">
					<span class="step-links">
						{% if uploads.has_previous %}
							<a href="?page={{ uploads.previous_page_number }}">previous</a>
						{% endif %}

						<span class="current">
						<h4>   Page {{ uploads.number }} of {{ uploads.paginator.num_pages }}. </h4>
						</span>

						{% if uploads.has_next %}
							<a class="btn btn-primary" href="?page={{ uploads.next_page_number }}">next</a>
						{% endif %}
					</span>
				</div> 
			</div>
		</div>
	{% endif %} 


	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</html>

instagram/templates/instagram/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="author" content="Sumedh_Karande">
		<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
		<title>Instagram-Login</title>

		<!-- Bootstrap -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" href="{% static 'instagram/style.css' %}" />
	</head>

	<!-- NAVBAR -->

	<nav class="navbar navbar-inverse navbar-default">
      	<div class="container">
        	<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynav">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" style="color: white" href="/">Instagram</a>
			</div>
			<div class="collapse navbar-collapse" id="mynav"> 
				<ul class="nav navbar-nav navbar-right">
					<li class="nav-item">
					<a class="nav-link" style="color: white" href="/instagram/signup">Sign-up</a>
					</li>
				</ul>
			</div> 
    	</div>
	</nav>

	 <!-- BODY OF THE LOGIN PAGE  -->

	<div class="container-fluid bg-3 text-center">
		<h1 class="align-center">Welcome back to Instagram</h1><br />
		<h2 class="align-center">Login</h2>
	</div>
	<br />
	{% if error %}

	<div style="width:250px; margin:0 auto;">
		<b style="font-size:16px;">{{error}}</b>
	</div>

	{% endif%}
	<div style="width:250px; margin:0 auto;">
		<form class="align-center" action="{% url 'instagram:login' %}" method="post" style="font-size:15px;">
			{% csrf_token %}
			<p>
				<label > Your username </label>
				<input type = "text" name = "username" />
			</p>
			<p>
				<label> Your password </label>
				<input type = "password" name = "password" />
			</p>
			<input class="btn btn-primary" type="submit" value="Login" />
		</form>
		<br />
		<li><a href="{% url 'instagram:signup' %}">Click here to create a new account</a></li>
	</div>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</html>

instagram/templates/instagram/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="author" content="Sumedh_Karande">
		<title>Instagram-Signup</title>

		<!-- Bootstrap -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" href="{% static 'instagram/style.css' %}" />
	</head>

	<!-- NAVBAR -->

	<nav class="navbar navbar-inverse navbar-default">
      	<div class="container">
        	<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynav">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
          		<a class="navbar-brand" style="color: white" href="/">Instagram</a>
        	</div>
			<div class="collapse navbar-collapse" id="mynav"> 
				<ul class="nav navbar-nav navbar-right">
					<li class="nav-item">
					<a class="nav-link" style="color: white" href="/instagram/login">Login</a>
					</li>
				</ul>
			</div> 
    	</div>
	</nav>

	<!-- BODY OF THE SIGNUP PAGE -->

	<div class="container-fluid bg-3 text-center">
		<h1 class="align-center">Welcome back to Instagram</h1>
		<h2 class="align-center">It’s free and always will be.</h2><br />
		<h3 class="align-center">Sign up to see photos and videos from your friends.</h3>
	</div>
	<br />
	{% if error %}
	<div style="width:150px; margin:0 auto;">
		<b style="font-size:18px;">{{error}}</b>
	</div>
	{% endif %}

	<div style="width:150px; margin:0 auto;">
		<form action="{% url 'instagram:signup' %}" method="post" style="font-size:15px;">
			{% csrf_token %}
			Username:
			<br />
			<input type="text" name="username" />
			Password:
			<br />
			<input type="password" name="password1" />
			Confirm Password:
			<br />
			<input type="password" name="password2" />
			<br />
			<br />
			<input class="btn btn-primary" type="submit" value="Sign-up" />
		</form>
		<br />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</html>